version: "3"

services:
  redis:
    image: "redis:alpine3.13"
    ports:
      - "6379:6379"
    command: "redis-server"
  aia:
    depends_on:
      - redis
    build: ./
    ports:
      - "5000:5000"
